
name: Build and Deploy java spring app to azure
on:
  push:
    branches:
      - master
  workflow_dispatch:   # To get Re-rub build tab in actions

env:
   
  JAVA_VERSION: '1.8'             

jobs:
  build:
    name: Build application source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Gradle
      run: |
        cd Application
        chmod +x gradlew
        ./gradlew build test bootwar
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: nanajanashia/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
